# Generated by Django 5.0.3 on 2024-04-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriety', '0002_proprietyvivienda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='password',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='proprietyvivienda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
