# Generated by Django 5.0.3 on 2024-04-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriety', '0003_rename_login_empleado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empleado',
            new_name='empleados',
        ),
        migrations.RenameModel(
            old_name='ProprietyVivienda',
            new_name='viviendas',
        ),
    ]
