# Generated by Django 5.0.3 on 2024-04-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriety', '0004_rename_empleado_empleados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
