# Generated by Django 5.0.3 on 2024-04-23 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriety', '0005_login_alter_empleados_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
